platform/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BE__c</fullName>
        <label>BE #</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>Site_Identifier__c</fullName>
        <label>Site Identifier</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_AU__c</fullName>
        <label>Store AU #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SIte</fullName>
        <active>true</active>
        <label>SIte</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

platform/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <formula>Project__r.Request_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Request Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_AU__c</fullName>
        <formula>Account.Primary_Au__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site AU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_AU__c</fullName>
        <formula>Account.Store_AU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store AU</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

platform/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Request_Name__c</fullName>
        <label>Request Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

platform/src/classes/VNET_SiteOrdersController.cls
/**
 * Created by fayle on 2/12/2016.
 */

public with sharing class VNET_SiteOrdersController {
    public Account              site { get; set; }
    public List<Opportunity>    orders { get; set; }

    public VNET_SiteOrdersController() {
        orders = new List<Opportunity>();
        String siteId = ApexPages.currentPage().getParameters().get('siteId');
        site = [SELECT Id, BE__c, Name, Site_Identifier__c, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode
                FROM Account WHERE Id = :siteId];
    }

    public void searchOrders() {
        orders = [SELECT Id, Name, Project__r.Name, Request_Name__c, Site_AU__c, Store_AU__c
                    FROM Opportunity WHERE AccountId = :site.Id];
    }
}